name: Ensuring Quality

on: [push, pull_request]

jobs:
  quality:
    name: Ensuring Quality
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Lint Markdown files
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: './README.md blog/post'
